[package]
name = "atrac3p-decoder-cli"
version = "0.1.0"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"

[dependencies]
atrac3p-decoder = { path = "../" }
rodio = { version = "0.11", default-features = false }

anyhow = "1.0"
env_logger = "0.7"
structopt = "0.3"