[package]
name = "cli"
version = "0.1.0"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"

[dependencies]
atrac3p = { path = "../" }

anyhow = "1.0"
structopt = "0.3"

rodio = { version = "0.11", default-features = false }